# -*- mode: ruby -*-
# vi: set ft=ruby :

ipythonPort = 5001                 

Vagrant.configure(2) do |config|
  config.vm.define "Python_machine" do |master|
    master.vm.box = "datascience-school/Python_machine"
    master.vm.box_download_insecure = true
    master.vm.boot_timeout = 900
   
    master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort, auto_correct: true
    master.vm.network :forwarded_port, host: 5000, guest: 5000, auto_correct: true
    master.vm.network :forwarded_port, host: 5002, guest: 5002, auto_correct: true
    master.vm.network :forwarded_port, host: 7474, guest: 7474, auto_correct: true
    master.vm.usable_port_range = 5000..5100
    
    master.vm.provider "virtualbox" do |v|
      v.name = "Python_machine"
      v.memory = 4096
      v.cpus = 1
    end
  end
end

