# -*- mode: ruby -*-
# vi: set ft=ruby :

ipythonPort = 8001                

Vagrant.configure(2) do |config|
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = true
  config.vm.define "Spark_machine" do |master|
    master.vm.box = "datascience-school/Spark_machine"
    master.vm.box_download_insecure = true
    master.vm.boot_timeout = 900
    
    master.vm.network :forwarded_port, host: ipythonPort, guest: ipythonPort, auto_correct: true   # IPython port (set in notebook config)
master.vm.network :forwarded_port, host: 4040, guest: 4040, auto_correct: true
    master.vm.usable_port_range = 4040..4090

    master.vm.provider "virtualbox" do |v|
      v.name = "Spark_machine"
      v.memory = 4096
      v.cpus = 1
    end
  end
end